import 'package:equatable/equatable.dart';

class UserPreview extends Equatable {
  /// Autogenerated
  final String id;

  /// "mr", "ms", "mrs", "miss", "dr", ""
  final String title;
  final String firstName;
  final String lastName;

  ///url
  final String picture;

  const UserPreview({
    required this.id,
    required this.title,
    required this.firstName,
    required this.lastName,
    required this.picture,
  });

  @override
  List<Object?> get props => [
        id,
        title,
        firstName,
        lastName,
        picture,
      ];
}
